spring:
  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA properties
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
# Server configuration
server:
  port: 8080
